# 
# Demodulator modules
#
itv-s5h1411-module-objs := is5h1411.o
itv-lgdt3305-module-objs := ilgdt3305.o

obj-$(CONFIG_iTV_FE_DEMOD_MODULE_S5H1411) += itv-s5h1411-module.o
obj-$(CONFIG_iTV_FE_DEMOD_MODULE_LGDT3305) += itv-lgdt3305-module.o
