#
# Makefile for the kernel character device drivers.
#
obj-y								         				+= audio/
obj-y								         				+= hdmi/
obj-y								         				+= cec/
obj-y								         				+= hpd/
obj-$(CONFIG_TCC_HDMI_STARTER)			+= hdmi_initial_start/
