# Makefile for TCCxxx isp driver
obj-$(CONFIG_USE_ISP) += drv_isp.o mrv_2str.o mrv.o mrv_col.o mrv_ie.o mrv_is.o mrv_isp.o mrv_jpe.o mrv_mif.o mrv_mipi.o mrv_regdump.o mrv_res.o mrv_si.o mrv_sls_dp.o mrv_sls_exif.o mrv_sls_jpe.o mrv_sls_snap.o mrv_smia.o mrv_smia_mipi.o mrv_smlout.o os.o sensor_parallel.o isp_interface.o
EXTRA_CFLAGS = -I$(src)/..
