obj-$(CONFIG_FB_TCC)	+= tca_fb_hdmi.o tca_fb_output.o tca_lcdc.o
obj-$(CONFIG_FB_TCC)	+= TCC_LCD_Interface.o dev_gpsb.o
obj-$(CONFIG_FB_TCC_COMPOSITE)	+= tcc_composite.o tcc_composite_internal.o 
obj-$(CONFIG_FB_TCC_COMPONENT)	  += tcc_component.o tcc_component_cs4954.o tcc_component_ths8200.o
