obj-$(CONFIG_RTC_DRV_TCC9200) += tca_rtc.o tca_alarm.o
obj-$(CONFIG_RTC_DRV_TCC9300) += tca_rtc.o tca_alarm.o
obj-$(CONFIG_RTC_DRV_TCC8800) += tca_rtc.o tca_alarm.o
obj-$(CONFIG_RTC_DRV_TCC8920) += tca_rtc.o tca_alarm.o
