# 
# Tuner modules
#
itv-xc5000-module-objs := ixc5000.o
itv-xc5000c-module-objs := ixc5000.o
itv-fqd1136-module-objs := ifqd1136.o
itv-fj2148-module-objs := ifj2148.o

obj-$(CONFIG_iTV_FE_TUNER_MODULE_XC5000) += itv-xc5000-module.o
obj-$(CONFIG_iTV_FE_TUNER_MODULE_XC5000C) += itv-xc5000c-module.o
obj-$(CONFIG_iTV_FE_TUNER_MODULE_FQD1136) += itv-fqd1136-module.o
obj-$(CONFIG_iTV_FE_TUNER_MODULE_FJ2148) += itv-fj2148-module.o
