# TCC Platform Support
snd-soc-tcc-pcm-objs := tcc-pcm.o tcc/tca_tcchwcontrol.o
snd-soc-tcc-i2s-objs := tcc-i2s.o
snd-soc-tcc-loopback-objs := tcc-loopback.o

obj-$(CONFIG_SND_SOC_TCC) += snd-soc-tcc-pcm.o
obj-$(CONFIG_SND_SOC_TCC_I2S) += snd-soc-tcc-i2s.o
obj-$(CONFIG_SND_TCC_LOOPBACK) += snd-soc-tcc-loopback.o

# TCC Machine Support
snd-soc-tcc-board-tcc250-objs := tcc_board_tcc250.o
snd-soc-tcc-board-wm8731-objs := tcc_board_wm8731.o
snd-soc-tcc-board-wm8524-objs := tcc_board_wm8524.o
snd-soc-tcc-board-wm8750-objs := tcc_board_wm8750.o
snd-soc-tcc-board-wm8993-objs := tcc_board_wm8993.o
snd-soc-tcc-board-wm8994-objs := tcc_board_wm8994.o
snd-soc-tcc-board-wm8988-objs := tcc_board_wm8988.o
snd-soc-tcc-board-es8388-objs := tcc_board_es8388.o
snd-soc-tcc-board-rt5625-objs := tcc_board_rt5625.o
snd-soc-tcc-board-rt5633-objs := tcc_board_rt5633.o
snd-soc-tcc-board-rt5631-objs := tcc_board_rt5631.o

obj-$(CONFIG_SND_SOC_TCC_BOARD_TCC250) += snd-soc-tcc-board-tcc250.o

obj-$(CONFIG_SND_SOC_TCC_BOARD_WM8524) += snd-soc-tcc-board-wm8524.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_WM8731) += snd-soc-tcc-board-wm8731.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_WM8750) += snd-soc-tcc-board-wm8750.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_WM8988) += snd-soc-tcc-board-wm8988.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_WM8993) += snd-soc-tcc-board-wm8993.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_WM8994) += snd-soc-tcc-board-wm8994.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_ES8388) += snd-soc-tcc-board-es8388.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_RT5625) += snd-soc-tcc-board-rt5625.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_RT5633) += snd-soc-tcc-board-rt5633.o
obj-$(CONFIG_SND_SOC_TCC_BOARD_RT5631) += snd-soc-tcc-board-rt5631.o
