# Makefile for TCCxxx camera driver

obj-$(CONFIG_VIDEO_ATV_SENSOR_RDA5888) += rda5888_atv.o rda5888app.o rda5888drv.o rda5888fm.o rda5888freqtbl.o rda5888mtk.o
obj-$(CONFIG_VIDEO_ATV_SENSOR_TVP5150) += tvp5150.o


EXTRA_CFLAGS = -I$(src)/..
